import { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  const baseUrl = 'https://egrow-academy.com';

  return {
    rules: [
      {
        userAgent: '*',
        allow: [
          '/',
          '/cursos',
          '/categorias',
          '/instructores',
          '/blog',
          '/eventos',
          '/sobre-nosotros',
          '/contacto',
          '/precios',
          '/testimonios',
          '/curso/*',
          '/categoria/*',
          '/instructor/*',
          '/blog/*',
          '/evento/*',
        ],
        disallow: [
          '/api/*',
          '/admin/*',
          '/dashboard/*',
          '/checkout/*',
          '/login',
          '/registro',
          '/perfil/*',
          '/mis-cursos/*',
          '/_next/*',
          '/static/*',
          '*.json',
          '*.xml',
        ],
      },
      {
        userAgent: 'Googlebot',
        allow: [
          '/',
          '/cursos',
          '/categorias',
          '/instructores',
          '/blog',
          '/eventos',
          '/curso/*',
          '/categoria/*',
          '/instructor/*',
          '/blog/*',
          '/evento/*',
        ],
        disallow: [
          '/api/*',
          '/admin/*',
          '/dashboard/*',
          '/checkout/*',
          '/login',
          '/registro',
          '/perfil/*',
          '/mis-cursos/*',
        ],
      },
      {
        userAgent: 'Bingbot',
        allow: [
          '/',
          '/cursos',
          '/categorias',
          '/instructores',
          '/blog',
          '/eventos',
          '/curso/*',
          '/categoria/*',
          '/instructor/*',
          '/blog/*',
          '/evento/*',
        ],
        disallow: [
          '/api/*',
          '/admin/*',
          '/dashboard/*',
          '/checkout/*',
          '/login',
          '/registro',
          '/perfil/*',
          '/mis-cursos/*',
        ],
      },
    ],
    sitemap: [
      `${baseUrl}/sitemap.xml`,
      `${baseUrl}/sitemap-image.xml`,
    ],
    host: baseUrl,
  };
} 